# Generated by Django 3.1.4 on 2021-02-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Degree_of_education', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('degree_of_education', models.ImageField(upload_to='')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.professor')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.university'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Maghale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Maghale', models.IntegerField()),
                ('title_Maghale', models.CharField(max_length=200)),
                ('Grouping_Maghale', models.CharField(max_length=200)),
                ('Owner', models.CharField(max_length=200)),
                ('Professor_Maghale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.student')),
            ],
        ),
        migrations.CreateModel(
            name='AddressUny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('st', models.CharField(max_length=20, verbose_name='street')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.university')),
            ],
        ),
    ]
