# Generated by Django 3.1.4 on 2021-02-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maghale',
            name='Owner',
        ),
    ]
