# Generated by Django 3.1.4 on 2021-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_remove_maghale_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='maghale',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
