# Generated by Django 3.1.4 on 2021-02-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0006_auto_20210214_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='Degree_of_education',
            new_name='Degree_of_education_p',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='degree_of_education',
            new_name='degree_of_education_p',
        ),
    ]
