# Generated by Django 3.1.4 on 2021-02-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0007_auto_20210214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maghale',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
