# Generated by Django 3.1.4 on 2021-02-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0008_auto_20210214_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
