# Generated by Django 3.1.4 on 2021-02-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0009_auto_20210214_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maghale',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project/pdfs/'),
        ),
    ]
