# Generated by Django 3.1.4 on 2021-02-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0012_auto_20210216_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressuny',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='addres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP1.addressuny'),
        ),
        migrations.AlterField(
            model_name='maghale',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='age_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP1.university'),
        ),
    ]
