# Generated by Django 3.1.4 on 2021-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0013_auto_20210217_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_of_education_p',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
