# Generated by Django 3.1.4 on 2021-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0014_auto_20210220_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age_s',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
