# Generated by Django 3.1.4 on 2021-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0015_auto_20210220_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_of_education_p',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
