# Generated by Django 3.1.4 on 2021-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0020_auto_20210221_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='Degree_of_education_p',
            field=models.ImageField(upload_to=''),
        ),
    ]
