# Generated by Django 3.1.7 on 2021-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0024_maghale_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='maghale',
            name='vaziat',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=20, null=True),
        ),
    ]
