# Generated by Django 3.1.7 on 2021-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0026_student_number_of_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number_of_student',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
